name = "docker-proxy"
type = "webpack"
account_id = "your account_id"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"
webpack_config = "webpack.config.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[vars]
MODE="production"
TARGET_UPSTREAM=""

[env.dev.vars]
MODE="debug"
TARGET_UPSTREAM="https://registry-1.docker.io"